<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitf6cf02a5a2d94624ba32542ab2664116
{
    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'MuhammadZeeshan\\Fms\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'MuhammadZeeshan\\Fms\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitf6cf02a5a2d94624ba32542ab2664116::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitf6cf02a5a2d94624ba32542ab2664116::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitf6cf02a5a2d94624ba32542ab2664116::$classMap;

        }, null, ClassLoader::class);
    }
}
