name: "CodeQL"

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  analyze:
    name: Analyze PHP
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL for PHP
        uses: github/codeql-action/init@v2
        with:
          languages: php

      - name: Manual setup step (not required for PHP)
        run: echo "PHP does not require build step."

      - name: Run CodeQL analysis
        uses: github/codeql-action/analyze@v2
